{% set version = "0.9.7" %}

package:
  name: httpretty
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/httpretty/httpretty-{{ version }}.tar.gz
  sha256: 66216f26b9d2c52e81808f3e674a6fb65d4bf719721394a1a9be926177e55fbe

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - httpretty

about:
  home: http://github.com/gabrielfalcao/httpretty
  license: MIT
  license_file: COPYING
  summary: HTTP client mocking tool for Python
  description: |
    HTTPretty is a HTTP client mock library for Python 100% inspired on
    Ruby's FakeWeb.
  doc_url: http://httpretty.readthedocs.org/
  dev_url: https://github.com/gabrielfalcao/httpretty

extra:
  recipe-maintainers:
    - ocefpaf
