{% set version = "0.9.4" %}

package:
  name: httpretty
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/httpretty/httpretty-{{ version }}.tar.gz
  sha256: 69259e22addf5ab5f25bd00c6568e16fc2e54efdd4da69eb0950718dba3b2dab

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - httpretty

about:
  home: http://github.com/gabrielfalcao/httpretty
  license: MIT
  license_file: COPYING
  summary: 'HTTP client mock for Python.'

extra:
  recipe-maintainers:
    - ocefpaf
