{% set version = "0.8.14" %}

package:
  name: httpretty
  version: {{ version }}

source:
  fn: httpretty-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/httpretty/httpretty-{{ version }}.tar.gz
  sha256: 83c176bbac9d68a45a5cca54f2d5be7e6b16a063adf6f334e7fd0eee272e976e

build:
  number: 0
  skip: True  # [py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - httpretty

about:
  home: http://github.com/gabrielfalcao/httpretty
  license: MIT
  license_file: COPYING
  summary: 'HTTP client mock for Python.'

extra:
  recipe-maintainers:
    - ocefpaf
