{% set version = "1.0.5" %}

package:
  name: httpretty
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/httpretty/httpretty-{{ version }}.tar.gz
  sha256: e53c927c4d3d781a0761727f1edfad64abef94e828718e12b672a678a8b3e0b5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - six

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - httpretty

about:
  home: http://github.com/gabrielfalcao/httpretty
  license: MIT
  license_file: COPYING
  summary: HTTP client mocking tool for Python
  description: |
    HTTPretty is a HTTP client mock library for Python 100% inspired on
    Ruby's FakeWeb.
  doc_url: http://httpretty.readthedocs.org/
  dev_url: https://github.com/gabrielfalcao/httpretty

extra:
  recipe-maintainers:
    - ocefpaf
