travis:
  secure:
    BINSTAR_TOKEN: kYQuFWxxt5Wd5hvSWGOsS4mfXK1QNq6hnPhlkDmbVKWkCyU4BPjozmeFTD1hlSDp8wc9+cayq8hYVfKvwjdasE6AHzSN2+ibPyJK2NoijXrSYGjuFL9N3x+h5Hl99gxwrkCta8HcBjd3BpL9ISGukKVpTLp9rQaSX/SoAqxsFe0LZdD7f1peUJQQ4r8Ro+tXQgazvaldGnd+MfamHvImA+Lzuk0sAgm31SFlsk09N4WoWpRee1g1TlZQbSBc1MjCzCRg1o2H+e/GW/F88GFfjT4+179/NSKrPAqtjnuZgoBaVIRQc5K0zMeyDp6udSbddCd9CeQBQcWCvgA9SQEkDWN8rICevNhsYKo8QSjGrfmo54k3bLe+nCfUjBE3fmamJU8d/6BpzKDNrh4edLT7+XWJ3VrOTlNlyzm+kU5u9bAH/XFUeg1GObceKE4I3gUrGdZLnhMObrK6aYVe/mR+WiE7AhC6+K2RQFQwURtSwm5hvc97XzQqK6BoVSvJgHv++9EcsNDuOqVeaCZVCqE5OLebU7v3ZJpaXOzfC6kvJkKP8P7iiOhqLNnO7octNegBbKDVUvvOjCXMcPzySVxogU+pnn4WM/W3I0VOVyyFb4mv67DH+J8NzuwM0euugL7vZkszamhCfcY7v25NYIj1+rRS6LVPDmrE+gVd/YfeVdg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
