travis:
  secure:
    BINSTAR_TOKEN: PRyRrDFacPgee6N9WHH7lkCbRzi9Y3HtJqe/VGNoIo5hqhUCarzUVBvQY9bqpSwuHuBh/tZzTCBSiXDIDUVev3KFbckRu4BY1LYTYmLM7ZxNrUl38AAhkPT0QmWhX5euZ3YmxliIHLF0vEEzZcs+I/lfEa9iVF02ur8hPvfXf8gYCHbrss4dyvTXfpIGTl4FX5LgdFLUTMF+DqDh10VjFoTB1Max7Tsyd/whfsKbHgGdJUN5rPiaEtfQUV4SG61YBWiH9InR1K/xcAJvusAeD0sfuj5SLJXhyWSoy4EGrqsK6UeR4aOx9LBLySzhoIEhESW7OnxduxTRSUc8HsxaOVJIO24YuwFxhtoubHp2iPGmrlHYlD5Z9WYBE0Mb7UcRkbbkKct/gJhNOlN7W25Em08ObyVnbruQAH7vUa7mrjnd88fwUjkWqY560tnShtdjAzM6ETTaiUwOuPSO9mTifGtOD9jM/J+sioGNoZzwcY33/rvdHSOiqEetCDKjXlvnaruon8hqPHMVuKAnT+11QUT0PBiz8SY9//D0NRwCRLmdMsO6RUHIB3JX2MLcBCLxRI/vDz15wCvP5BuLWppTS0HSJiyXBw+nwlOkrxs1i5sBbd5MY9Lz2+d+MEu/vK+qemQ38XbckieDdwFda/O9HgXwMd68cb0sOHdBvLGUVJ0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
