travis:
  secure:
    BINSTAR_TOKEN: izEuSA6tCLEfVSKJI5fjAkHe3wFIvrpQ5S1wFT3ZiMJbwqBEFRan4/Kfh2QFMjC9KpJB3xjWhA4DDhyT3QQiZkQd66AdXCNkOeXcvruryF9uiaBWtIC7ZdTRzR8iq4H2iovWpPLneD7gL+nhjdzR2r4GWyF36lLQNU4jrQWlWP9PZE1dYcRXLz1e9H34C0Ivi5z7Hu2MFOJNgHyqyAXempO9rzwTpol5Ag7UVcHfgOKMJKakDY0aZIU4QjrNhx6xh8v/s1MFcMsMSPWRA7Q/Tb/C5Qy4GikOlOZ0X0pKKd7hvEc+CDBCWwaVJ0EhmmQXkFl2sJM1LJOYw1pMOXluGH9EriyILYDvnX0Gx8GXgCIeQ/8nVa6UC65A6GHDY4gG1WNBzfyG9XM7WNAckOt8fgQLG8EpCOpEnvXXj2jEBeaGe8kgpTU0YWEwDcQVvojdpiBABvEftP2ogqlx6kntCrum3ZWjKxb3y2oEPtHqt6s8GBz5juoCO4+MAtbiOfwB3QrA9WUEm46jkUARV4gMVix2oyJfu642Is3tmC9ZCsdZpa0Zww15PyVXNbybR3rNEiZccBoDywAGlmlCayXG66kj4g+uf+6zqBflr4O2VzUNx0FfwzSdM/pG4je46UYHioZ/nkNBquTZS/PHEkKLIrS9M7QLi2gV9iNfj05keeg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
